### PR TITLE
Add packaging for Linux CPython x86_64

### PR DESCRIPTION
**Pull request by frodon1**
The packaging was added for CPython x86_64 on Linux, from python 3.7 to python 3.13.
Some porting was added in specific commits for portability to python 3.12 and 3.13.
Additional porting in the build procedure needs to be done for those versions on Windows.

The build mechanism for Linux is based on cibuildwheel.

### CODE REVIEW

**Comment by frodon1** [comment]
This PR fixes #1 and #3 on Linux.

**Comment by frodon1** [comment]
@ksmyth any chance you can have a look at my PR ? Thanks !

**Comment by ksmyth** [comment]
Thanks for the PR. The Linux .whl looks good as far as I can tell. However, the Windows .whls changed.

1. Could you please modify the build so that these files (and similarly-named) aren't included in the .whl:

```
omniORB/GNUmakefile
omniORB/GNUmakefile.in
omniORB/dir.mk
```

2. `COS/omniORB.pth` contains `omniORBCOS` on windows, but `omniORB/COS` on Linux. Perhaps this is a backslash escape character error? But on Windows, the `COS` directory is installed directly in `site-packages`, which makes the .pth file unnecessary. So I think the best fix is to exclude this file on Windows.

Please make these changes, then I'll merge the PR.

**Comment by frodon1** [comment]
The corrections were made, the wheels for Windows seem fine now.
Best regards

**Comment by ksmyth** [comment]
Looks good, thanks very much.

**Comment by frodon1** [comment]
My pleasure, any idea when the linux wheels will be available on pypi?

**Comment by ksmyth** [comment]
"linux" wheels are rejected by pypi. The omniORB build has `repair-wheel-command = ""`, which is the step that normally converts "linux" wheels into "manylinux" wheels. I don't know offhand how to make the repair-wheel work.

**Comment by frodon1** [comment]
Hello @ksmyth , please see my other PR https://github.com/metamorph-inc/omniORB/pull/6

**Pull request merged**
